# Generated by Django 4.0 on 2021-12-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sNombre', models.CharField(max_length=100, null=True)),
                ('sPaterno', models.CharField(max_length=100, null=True)),
                ('sMaterno', models.CharField(max_length=100, null=True)),
                ('dEstatura', models.FloatField(null=True)),
                ('dPeso', models.FloatField(null=True)),
                ('dImc', models.FloatField(null=True)),
            ],
        ),
    ]
